spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/zzangzzang
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect