spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/zzangzzang
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: eunsun5460@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000