spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/zzangzzang
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: eunsun5460@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  redis:
    host: 127.0.0.1
    port: 6379


springdoc:
  packages-to-scan: com.eunsunzzang.posting
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M
